// web-quiz/react-ts/src/views/game/GameOver.tsx
import { useGame } from '@/hooks/useGame';
import { Link } from 'react-router';
import './GameOver.css';

const GameOver = ({ onResetGame }: { onResetGame: () => void }) => {
  const { score } = useGame();

  return (
    <>
      <h1>Game Over</h1>
      <h3>Score: {score}</h3>
      <button onClick={() => onResetGame()}>Try Again</button>
      <Link to="/">Home</Link>
    </>
  );
};

export default GameOver;

// web-quiz/vue-ts/src/views/GameOver.vue
<template>
  <h1>Game Over</h1>
  <h3>Score: {{ gameStore.score }}</h3>
  <button @click="gameStore.$reset()">Try Again</button>
  <routerLink to="/">Home</routerLink>
</template>

<script setup lang="ts">
import { useGameStore } from '@/store/game';

const gameStore = useGameStore();
</script>

<style scoped>
button {
  margin-right: 10px;
}
</style>
