// web-quiz/react-ts/src/views/game/Game.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import './Game.css';

import QuizQuestions from '@/components/QuizQuestion';
import { useGame } from './GameProvider';

function Game() {
  const navigate = useNavigate();
  const { questionNumber, score, setQuestions } = useGame();

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(
          'https://opentdb.com/api.php?amount=10&category=15&type=multiple'
        );
        const json = await response.json();

        if (json.response_code === 5) {
          throw new Error('Too Many Requests');
        }

        setQuestions(json.results);
        setLoading(false);
      } catch {
        navigate('/error');
      }
    };

    fetchData();
  }, [navigate, setQuestions]);

  return (
    <>
      <div className="game">
        {loading ? (
          <h1>Loading Quiz...</h1>
        ) : (
          <div>
            <div className="game-info">
              <div className="left">
                <h3> {questionNumber} / 10</h3>
              </div>
              <div className="right">
                <div>
                  <h3>Score: {score}</h3>
                  <h3>Time: </h3>
                </div>
                <div></div>
              </div>
            </div>
            <QuizQuestions />
          </div>
        )}
      </div>
    </>
  );
}

export default Game;

// web-quiz/vue-ts/src/views/Game.vue
<template>
  <div>
    <h1 v-if="loading">Loading Quiz...</h1>
    <div v-else>
      <span>{{ gameStore.questionNumber }}</span>
      <quiz-question />
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';

import { useGameStore } from '@/store/game';

import QuizQuestion from '@/components/QuizQuestion.vue';

const router = useRouter();
const gameStore = useGameStore();

const loading = ref(true);

const fetchQuizData = async () => {
  try {
    const response = await fetch('https://opentdb.com/api.php?amount=10&category=15&type=multiple');
    const json = await response.json();

    if (json.response_code === 5) {
      throw new Error('Too Many Requests');
    }

    loading.value = false;
    gameStore.setQuestions(json.results);
  } catch {
    router.push({ name: 'error' });
  }
};

onMounted(() => {
  fetchQuizData();
});
</script>
