// web-quiz/react-ts/src/components/quizQuestions.tsx/QuizQuestion.tsx
import { useMemo } from 'react';
import { useGame } from '@/hooks/useGame';
import { getRandomNumber } from '@/helpers/getRandomNumber';
import './QuizQuestions.css';

const QuizQuestions = () => {
  const { currentQuestion, nextQuestion } = useGame();

  const answers = useMemo(() => {
    if (!currentQuestion) return [];
    const currentAnswers = currentQuestion.incorrect_answers.map((ans) => ({
      answer: ans,
      correct: false
    }));
    currentAnswers.splice(getRandomNumber(3), 0, {
      answer: currentQuestion.correct_answer,
      correct: true
    });

    return currentAnswers;
  }, [currentQuestion]);

  return (
    <>
      <h2 dangerouslySetInnerHTML={{ __html: currentQuestion?.question ?? '' }}></h2>
      <div className="answers">
        {answers.map((answer, index) => (
          <button
            key={index}
            onClick={() => nextQuestion(answer.correct)}
            dangerouslySetInnerHTML={{ __html: answer.answer }}
          ></button>
        ))}
      </div>
    </>
  );
};

export default QuizQuestions;

// web-quiz/vue-ts/src/components/QuizQuestion.vue
<template>
  <h2 v-html="gameStore.currentQuestion.question"></h2>
  <div class="answers">
    <button
      v-for="answer of answers"
      @click="answerQuestion(answer.correct)"
      v-html="answer.answer"
    ></button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

import { getRandomNumber } from '@/helpers/getRandomNumber';

import { useGameStore } from '@/store/game';

const gameStore = useGameStore();

const answers = computed(() => {
  let currentAnswers = gameStore.currentQuestion.incorrect_answers.map((ans) => ({
    answer: ans,
    correct: false
  }));
  currentAnswers.splice(getRandomNumber(3), 0, {
    answer: gameStore.currentQuestion.correct_answer,
    correct: true
  });

  return currentAnswers;
});

const answerQuestion = (correct_answer: boolean) => {
  gameStore.nextQuestion(correct_answer);
};
</script>

<style scoped>
.answers {
  display: grid;
  grid-template-columns: 1fr 1fr;

  button {
    margin: 10px;
  }
}
</style>
